CREATE SEQUENCE DEP_ID_SQD
INCREMENT BY 10
START WITH 120
MAXVALUE 9999;

CREATE TABLE DEPARTMANETO(
    DEP_COD NUMBER(3) NOT NULL,
    DEP_NOME VARCHAR2(30)
);

SELECT * FROM USER_SEQUENCES;
INSERT INTO DEPARTMANETO VALUES(DEP_ID_SQD.nextval, 'Vendas');
INSERT INTO DEPARTMANETO VALUES(DEP_ID_SQD.nextval, 'RH');


SELECT * FROM DEPARTMANETO;

select DEP_ID_SQD.currval from dual

ALTER SEQUENCE DEP_ID_SQD
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO DEPARTMANETO VALUES(DEP_ID_SQD.nextval, 'Informática');
SELECT * FROM DEPARTMANETO;

DROP SEQUENCE DEP_ID_SQD