-- BTS_BATES (BTS_CNPJ, BTS_HORARIO_CHECKOUT, 
--            BTS_HORARIO_CHECKIN, BTS_ENDERECO)


CREATE TABLE BTS_BATES(
    BTS_CNPJ NUMBER(11),
    -- VERIFICAR SE DEVERÁ SER SALVO EM DATA E USAR to_char(sysdate,'HH.MI.SS') PARA EXTRAIR
    -- OU USAR CHAR
    BTS_HORARIO_CHECKIN DATE,
    BTS_HORARIO_CHECKOUT DATE,
    BTS_ENDERECO VARCHAR(100),

    CONSTRAINT BTSPK PRIMARY KEY (BTS_CNPJ)
);

-- SLT_SALA_DE_TRABALHO (SLT_NUMERO, 
--                      SLT_SETOR, SLTR_TIPO, BTS_CNPJ)

CREATE TABLE SLT_SALA_DE_TRABALHO(
    SLT_NUMERO NUMBER(3),
    SLT_SETOR NUMBER(3),
    SLTR_TIPO VARCHAR(15),
    BTS_CNPJ NUMBER(11),

    CONSTRAINT SLTPK PRIMARY KEY (SLT_NUMERO),
    CONSTRAINT SLTFK FOREIGN KEY (BTS_CNPJ) REFERENCES BTS_BATES(BTS_CNPJ)
);

-- AND_ANDAR (AND_NUMERO, BTS_CNPJ)
CREATE TABLE AND_ANDAR(
    AND_NUMERO NUMBER(3),
    BTS_CNPJ NUMBER(11),
    
    CONSTRAINT ANDPK PRIMARY KEY (AND_NUMERO),
    CONSTRAINT ANDFK FOREIGN KEY (BTS_CNPJ) REFERENCES BTS_BATES(BTS_CNPJ)

);