CREATE TABLE TABELA1(
    COLUNA1 NUMBER(3),
    COLUNA2 VARCHAR2(30)    
);

CREATE TABLE TABELA2(
    COLUNA1 NUMBER(3),
    COLUNA2 VARCHAR2(30)    
);

INSERT INTO TABELA1 VALUES(1,'LINHA 1 DA TABELA1');
INSERT INTO TABELA1 VALUES(2,'LINHA 2 DA TABELA1');
INSERT INTO TABELA1 VALUES(3,'LINHA 3 DA TABELA1');

INSERT INTO TABELA2 VALUES(1,'LINHA 1 DA TABELA2');
INSERT INTO TABELA2 VALUES(2,'LINHA 2 DA TABELA2');
INSERT INTO TABELA2 VALUES(3,'LINHA 3 DA TABELA2');

-- SQL

-- JOINS
-- NATURAL JOIN 
-- O Natural Join junta os dados de duas tabelas sem ser necessário especificar as colunas.
-- * É necessário que a tabela possua a coluna com mesmo nome e tipo de dado
SELECT COLUNA2 FROM TABELA1
NATURAL JOIN TABELA2