CREATE TABLESPACE  TS_PBD3_2019
DATAFILE  'C:\BD\TS_PBD3_2019.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_PRATICA03
IDENTIFIED BY aluno
DEFAULT TABLESPACE TS_PBD3_2019
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_PBD3_2019;

GRANT DBA TO USER_PRATICA06 WITH ADMIN OPTION;