CREATE OR REPLACE TRIGGER TRACKSALEMPREGADO
BEFORE INSERT OR UPDATE OR DELETE ON EMPREGADO
FOR EACH ROW
BEGIN

  IF INSERTING THEN
    -- SE FOI INSERIDO, APENAS ATUALIZA O SALARIO DO DEPARTAMENTO
    UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL + :new.SALARIO WHERE NOME = :new.DEPTO;
  END IF;
  
  IF DELETING THEN 
    UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL - :new.SALARIO WHERE NOME = :new.DEPTO;
  END IF;
  
  IF UPDATING THEN
  
    CASE :NEW.DEPTO
        WHEN :NEW.DEPTO <> :OLD.DEPTO THEN UPDATE DEPARTAMENTO WHERE NOME = :OLD.DEPTO SET TOTAL_SAL = TOTAL_SAL - :OLD.SALARIO;
        WHEN :NEW.DEPTO == :OLD.DEPTO THEN UPDATE DEPARTAMENTO WHERE NOME = :OLD.DEPTO SET TOTAL_SAL = TOTAL_SAL + :NEW.SALARIO;
    END CASE;
   
  END IF;
  
END TRACKSALEMPREGADO;