-- Mateus Machado

CREATE TABLE EMPREGADO(
  CPF NUMBER(8),
  NOME VARCHAR2(100),
  DEPTO VARCHAR2(100),
  SALARIO NUMBER(8),

  CONSTRAINT EMPK PRIMARY KEY (CPF)
);

CREATE TABLE DEPARTAMENTO(
  COD NUMBER(8),
  NOME VARCHAR2(100),
  TOTAL_SAL VARCHAR2(100),
  CONSTRAINT DPPK PRIMARY KEY (COD)
);


CREATE OR REPLACE TRIGGER TRACKSALEMPREGADO
BEFORE INSERT OR UPDATE OR DELETE ON EMPREGADO
FOR EACH ROW
BEGIN

  IF INSERTING THEN
    -- SE FOI INSERIDO, APENAS ATUALIZA O SALARIO DO DEPARTAMENTO
    UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL + :new.SALARIO WHERE NOME = :new.DEPTO;
  END IF;
  
  IF DELETING THEN 
  -- SE ESTÁ SENDO DELETADO, O TOTAL_SALARIO DO DEPARTAMENTO É DECREMENTADO
    UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL - :OLD.SALARIO WHERE NOME = :OLD.DEPTO;
  END IF;
  
  IF UPDATING THEN
    -- SE O UPDATE PRESERVA O DEPARTAMENTO
    IF :NEW.DEPTO <> :OLD.DEPTO THEN 
        -- CHECANDO SE O SALARIO DIMINUIU OU AUMENTOU
        IF :NEW.SALARIO > :OLD.SALARIO THEN
            UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL - :OLD.SALARIO WHERE NOME = :OLD.DEPTO ;
        ELSE
            UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL + :OLD.SALARIO WHERE NOME = :OLD.DEPTO ;
        END IF;
    -- SE O UPDATE ALTERA O DEPARTAMENTO DO FUNCIONARIO DIMINUI O SALARIO TOTAL DO DEPARTAMENTO ANTIGO E AUMENTA O DO NOVO   
    ELSE
        UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL - :OLD.SALARIO WHERE NOME = :OLD.DEPTO;
        UPDATE DEPARTAMENTO SET TOTAL_SAL = TOTAL_SAL + :OLD.SALARIO WHERE NOME = :NEW.DEPTO;
    END IF;
   
  END IF;
  
END TRACKSALEMPREGADO;